[package]
name = "rustls-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"

[[bin]]
name = "client"

[dependencies]
rustls = { version = "0.23.4", features = ["ring", "aws_lc_rs"] }
#rustls = { version = "0.22.*" }
rustls-pemfile = "2.1.2"
env_logger = "0.11.3"
log = "0.4.21"
